name: Backend Format Check
on: pull_request
jobs:
  dotnet_format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui-android

      - name: Run dotnet format
        run: |
          if [ -f 'Urd.csproj' ]; then
            dotnet format 'Urd.csproj' --exclude 'addons' --verify-no-changes
          else
            echo "No .csproj file found, skipping format check."
          fi
